### ISSUE TITLE
Custom error raised in Python model was not passed back to the client

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#974]
seldon-core: installed from master branch
s2i: 0.13-SNAPSHOT
operator: 0.4.1

I was following the [User Defined Exceptions](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#user-defined-exceptions) to create a customized error. My predict function in model class looks like:

```
    def predict_raw(self, msg: prediction_pb2.SeldonMessage) -> dict:
        try:
            do_something(data)
        except UserCustomException as e:
            raise UserCustomException(
                f"message", e.application_error_code, e.status_code
            ) from e
```

I was sending `curl` request from command line, but I was getting

```
{
  "code": 203,
  "info": "Failed to retrieve predictions after 3 attempts",
  "reason": "Microservice error",
  "status": "FAILURE"
}
``` 

as response.

Logs in my model has the correct error code but it is not passed back to client properly:

```
2019-10-21 14:56:14,664 - werkzeug:_log:122 - INFO:   * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2019-10-21 15:18:59,496 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [21/Oct/2019 15:18:59] "POST /predict HTTP/1.1" 123 -
2019-10-21 15:18:59,506 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [21/Oct/2019 15:18:59] "POST /predict HTTP/1.1" 123 -
2019-10-21 15:18:59,509 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [21/Oct/2019 15:18:59] "POST /predict HTTP/1.1" 123 -
```

logs in container did not include the response either:

```
2019-10-21 15:18:58.310 DEBUG 6 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : Seldon graph ready: true
2019-10-21 15:18:59.403 DEBUG 6 --- [nio-8000-exec-1] i.s.e.api.rest.RestClientController      : Received predict request
2019-10-21 15:18:59.430 DEBUG 6 --- [cTaskExecutor-2] i.s.e.predictors.PredictiveUnitBean      : Add metrics
2019-10-21 15:18:59.431  INFO 6 --- [cTaskExecutor-3] i.s.e.service.InternalPredictionService  : Calling grpc for transform-in
put
2019-10-21 15:18:59.442 DEBUG 6 --- [cTaskExecutor-3] i.s.e.service.InternalPredictionService  : Requesting http://localhost:9
000/predict
2019-10-21 15:18:59.504  WARN 6 --- [cTaskExecutor-3] i.s.e.service.InternalPredictionService  : Caught resource access except
ion
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9000/predict": localho
st:9000 failed to respond; nested exception is org.apache.http.NoHttpResponseException: localhost:9000 failed to respond
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:674) ~[spring-web-4.3.20.RELEASE.jar!/:4.3.
20.RELEASE]
        at ...
``` .

**Comment by axsaucedo** [comment]
@lennon310 thanks for submitting the issue. Currently we have #705 open as you correctly point out, the engine doesn't pass the exceptions upstream. The error code itself I don't think it's handled either so perhaps this issue could be kept open to address this unless we'd prefer to merge both.

**Comment by lennon310** [comment]
Thanks @axsaucedo for addressing this.
A related question: is there a reason why we cannot set http status code in response directly rather than asking clients to handle a customized exception as it is now?
Would that be equivalent if we change something in wrapper like [this](https://github.com/SeldonIO/seldon-core/compare/master...lennon310:status_code) so we probably don't need to add customized error handling logic in model prediction?

**Comment by axsaucedo** [comment]
@lennon310 that actually looks like a pretty reasonable solution! We would just have to make sure that it is sound across both REST and GRPC, but definitely a reasonable fix. Would you be able to open a PR with a few tests (an [end-to-end test](https://github.com/SeldonIO/seldon-core/tree/master/testing/scripts) would be fantastic as well)?

**Comment by cliveseldon** [comment]
Fixed by #1010

**Comment by gosandhya** [comment]
I am using Seldon version 1.5.0 and still seeing this issue. The curl request shows the custom error message but it is not being passed to the client. Not sure if I am missing something. Can someone help me out here?
